baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "github-style"

[[menu.main]]
    name = "About"
    url = "https://matthewkrachey.netlify.app"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/aerotuck/portfolio"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/KracheyMatthew"
