baseurl = "/"
languageCode = "en-us"
title = "Matthew Kracheys Homepage"
theme = "toha"
enableEmoji = true	


[[params]]
    author = "Matthew Krachey"
    gitRepo = "https://github.com/aerotuck/portfolio"
    gitBranch = "main"
    enableTOC = true
    enableBlogPost = true

[[menu.main]]
    name = "About"
    url = "https://matthewkrachey.netlify.app"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/aerotuck/portfolio"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/KracheyMatthew"
