baseurl = "/"
languageCode = "en-us"
title = "Matthew Kracheys Homepage"
theme = "hugo-lithium-theme"
enableEmoji = true	
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]


[[params]]
    author = "Matthew Krachey"
    gitRepo = "https://github.com/aerotuck/portfolio"
    gitBranch = "main"
    enableTOC = true
    enableBlogPost = true
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/aboutme/aboutme.html"
    weight = 2
[[menu.main]]
   name = "GitHub"
    url = "https://github.com/aerotuck/portfolio"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/files/Krachey.pdf"
    weight = 4
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/KracheyMatthew"
    weight = 5




